// flow-typed signature: 46cd1980f64b01733314858dd784205d
// flow-typed version: <<STUB>>/@atomix/eslint-config_v^8.0.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atomix/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atomix/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atomix/eslint-config/example' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atomix/eslint-config/example.js' {
  declare module.exports: $Exports<'@atomix/eslint-config/example'>;
}
