// flow-typed signature: dc56354bb0736cacaf99b2405e824340
// flow-typed version: <<STUB>>/koa-websocket_v^6.0.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-websocket'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-websocket' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-websocket/examples/koa-router' {
  declare module.exports: any;
}

declare module 'koa-websocket/examples/simple' {
  declare module.exports: any;
}

declare module 'koa-websocket/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-websocket/examples/koa-router.js' {
  declare module.exports: $Exports<'koa-websocket/examples/koa-router'>;
}
declare module 'koa-websocket/examples/simple.js' {
  declare module.exports: $Exports<'koa-websocket/examples/simple'>;
}
declare module 'koa-websocket/index' {
  declare module.exports: $Exports<'koa-websocket'>;
}
declare module 'koa-websocket/index.js' {
  declare module.exports: $Exports<'koa-websocket'>;
}
declare module 'koa-websocket/test/test.js' {
  declare module.exports: $Exports<'koa-websocket/test/test'>;
}
