// flow-typed signature: dd01fe1da72607b9f38554b7d164ad0e
// flow-typed version: <<STUB>>/koa2-cors_v^2.0.6/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa2-cors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa2-cors' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa2-cors/dist' {
  declare module.exports: any;
}

declare module 'koa2-cors/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa2-cors/dist/index' {
  declare module.exports: $Exports<'koa2-cors/dist'>;
}
declare module 'koa2-cors/dist/index.js' {
  declare module.exports: $Exports<'koa2-cors/dist'>;
}
declare module 'koa2-cors/src/index' {
  declare module.exports: $Exports<'koa2-cors/src'>;
}
declare module 'koa2-cors/src/index.js' {
  declare module.exports: $Exports<'koa2-cors/src'>;
}
